# Config file

# Directories
rawdata_dir: "rawdata"
rawdata_subdirs:
  landcover_dir: "landcover"
  era5_dir: "era5"
data_dir: "data"
data_subdirs:
  psd_dir: "psd"
  landcover_proc_dir: "landcover_proc"
figure_dir: "figures"
fig_subdirs:
  correlations: "corr_matrices"
  pre_vis: "pre_visualizations"
  model_vis: "model_visualizations"

# File locations
landcover_txt_files_dir: "src/src_landcover/txt_files"
landcover_legend_dir: "src/src_landcover"

# Sample point for PSD example
sample_point_idx:
  lat: 40     # corresponding to 40N
  lon: 120    # corresponding to 100W
  year: 2020

# Plotting
save_figs: True
seed: 42
dpi: 300

# PSD processing parameters
bandwidth: 2  # time-bandwith product for the MTM spectral estimation (controls spectral leakage)
k_tapers: 3   # Number of tapers for the MTM spectral estimation
conf_ratio_exp: -9  # Exponent for confidence level for white noise detection (1 - 10^conf_ratio_exp)

# Temporal and spatial
years: ['2000', '2005', '2010', '2015', '2020']
area_bounds: [50, -130, 25, -70]  # N, W, S, E

# Landcover correlations
decimation: 1
method: 'daily' # daily or br (for breakpoint)
block_size: 10  # block size for block bootstrap
n_bootstrap: 500  # number of bootstrap samples


